export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_CATERERS = 'FETCH_CATERERS';
export const FETCH_ACCOMODATIONS = 'FETCH_ACCOMODATIONS';
export const FETCH_BEAUTICIANS = 'FETCH_BEAUTICIANS';
export const FETCH_FLORISTS = 'FETCH_FLORISTS';
export const FETCH_MUSICOPTIONS = 'FETCH_MUSICOPTIONS';
export const FETCH_PHOTOGRAPHERS = 'FETCH_PHOTOGRAPHERS';
export const FETCH_VENUES = 'FETCH_VENUES';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const FETCH_EVENT_FEEDBACKS = 'FETCH_EVENT_FEEDBACKS';
export const CREATE_EVENT_FEEDBACK = 'CREATE_EVENT_FEEDBACK';
export const DELETE_EVENT_FEEDBACK = 'DELETE_EVENT_FEEDBACK';

export const FETCH_PACKAGES = 'FETCH_PACKAGES';
export const UPDATE_PACKAGE = 'UPDATE_PACKAGE';
export const FETCH_PACKAGE_FEEDBACKS = 'FETCH_PACKAGE_FEEDBACKS';
export const CREATE_PACKAGE_FEEDBACK = 'CREATE_PACKAGE_FEEDBACK';
export const DELETE_PACKAGE_FEEDBACK = 'DELETE_PACKAGE_FEEDBACK';
