const cities = [
  'Delhi',
  'Bangalore',
  'Mumbai',
  'Kolkata',
  'Adoni',
  'Amaravati',
  'Anantapur',
  'Chandragiri',
  'Chittoor',
  'Dowlaiswaram',
  'Eluru',
  'Guntur',
  'Kadapa',
  'Kakinada',
  'Kurnool',
  'Machilipatnam',
  'Nagarjunakoṇḍa',
  'Rajahmundry',
  'Srikakulam',
  'Tirupati',
  'Vijayawada',
  'Visakhapatnam',
  'Vizianagaram',
  'Yemmiganur',
  'Hyderabad',
  'Karimnagar',
  'Khammam',
  'Mahbubnagar',
  'Nizamabad',
  'Sangareddi',
  'Warangal',
];

export default cities;
